name: CI/CD Pipeline - Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        id: build_push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ilshz/rege-app:latest

  deploy:
    name: Deploy to Remote Server
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.DEPLOY_SERVER }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            echo "Pulling new Docker image..."
            docker pull ilshz/rege-app:latest
            echo "Stopping old container (if exists)..."
            docker stop rege-app || true
            docker rm rege-app || true
            echo "Running new container..."
            docker run -d --name rege-app -p 3000:3000 ilshz/rege-app:latest

